config/routes.rb
Rails.application.routes.draw do
  get 'archives/index'
  resources :entries
  root to: "entries#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord

    validates :calories, :proteins, :carbohydrates, :fats, :meal_type, presence:true
    def day
        self.created_at.strftime("%b %e, %Y")
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
    @entries = Entry.all.group_by(&:day)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.where("created_At >= ?", Date.today)
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:meal_type, :calories, :proteins, :carbohydrates, :fats)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/archives/index.html.erb
<div class="columns is-centered mt-6">
    <div class="column is-half">
        <% @entries.each do |day, entries| %>
        <h3 class="is-size=4 has-text-weight-bold mb-4 has-text-centered">Entries for <%= day %></h3>
            <nav class="level is-mobile">
                <div class="level-item has-text-centered">
                    <div>
                        <p class="heading">Calories</p>
                        <p class="title"><%= entries.pluck(:calories).sum %></p>
                    </div>
                </div>
                <div class="level-item has-text-centered">
                    <div>
                        <p class="heading">Proteins</p>
                        <p class="title"><%= entries.pluck(:proteins).sum %>g</p>
                    </div>
                </div>
                <div class="level-item has-text-centered">
                    <div>
                        <p class="heading">Carbohydrates</p>
                        <p class="title"><%= entries.pluck(:carbohydrates).sum %>g</p>
                    </div>
                </div>
                <div class="level-item has-text-centered">
                    <div>
                        <p class="heading">Fats</p>
                        <p class="title"><%= entries.pluck(:fats).sum %>g</p>
                    </div>
                </div>
            </nav>
            <% entries.each do |entry|%>
                <%= link_to entry_path(entry) do %>
                    <div class="card">
                        <div class="card-content">
                            <strong><%= entry.meal_type %></strong><br/>
                            <%= entry.calories %> calories,
                            <%= entry.proteins %>g protein,
                            <%= entry.carbohydrates %>g carbs,
                            <%= entry.fats %>g fat,
                        </div>
                    </div>
                <% end %>
            <% end %>
        <% end %>
    </div>
</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div id="message is-danger">
      <div class="message-header">
        <p><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</p>
      </div>
      <div class="message-body">
        <ul>
          <% entry.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :meal_type, class:"label" %>
    <%= form.text_field :meal_type, class:"input" %>
  </div>

  <div class="field">
    <%= form.label :calories, class:"label" %>
    <%= form.number_field :calories, class:"input" %>
  </div>

  <div class="field">
    <%= form.label :proteins, class:"label" %>
    <%= form.number_field :proteins, class:"input" %>
  </div>

  <div class="field">
    <%= form.label :carbohydrates, class:"label" %>
    <%= form.number_field :carbohydrates, class:"input" %>
  </div>

  <div class="field">
    <%= form.label :fats, class:"label" %>
    <%= form.number_field :fats, class:"input" %>
  </div>

  <div class="actions">
    <%= form.submit class:"button is-success" %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<div class="columns is-centered mt-6">
    <div class="column is-one-third">
        <h1 class="is-size-2 has-text-weight-bold mb-3">Editing entry</h1>
        <%= render 'form', entry: @entry %>
    </div>
</div>

app/views/entries/index.html.erb
<% content_for :title do %>
  Foodlog &ndash; <%= DateTime.now.to_s(:nice_date) %>
<% end %>

<div class="columns mt-6 is-centered">
    <% @entries.each do |entry| %>
      <div class="column is-one-quarter">
      <div class="card">
      <header class="card-header">
      <p class="card-header-title">
        <%= entry.meal_type %>
        </p>
      </header>
      <div class="card-content">
        <div class="content">
          <p><span class="has-text-weight-bold"><%= entry.calories %></span> calories</p>
          <p><span class="has-text-weight-bold"><%= entry.proteins %></span> grams of protein</p>
          <p><span class="has-text-weight-bold"><%= entry.carbohydrates %></span> grams of carbohydrates</p>
          <p><span class="has-text-weight-bold"><%= entry.fats %></span> grams of fat</p>
          <p class="italic">Logged <%= time_ago_in_words(entry.created_at)%> ago</p>
        </div>
      </div>
      <div class="card-footer">
        <%= link_to 'Show', entry, class: "card-footer-item" %>
        <%= link_to 'Edit', edit_entry_path(entry), class: "card-footer-item" %>
        <%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' }, class: "card-footer-item" %>
        </div>
      </div>
      </div>
    <% end %>
</div>

<div class="columns is-centered mt-6">
  <%= link_to "View all entries", archives_index_path, class:"button is-link is-outlined is-centered" %>
</div>

app/views/entries/new.html.erb
<div class="columns is-centered mt-6">
    <div class="column is-one-third">
        <h1 class="is-size-2 has-text-weight-bold mb-3">New entry</h1>
        <%= render 'form', entry: @entry %>
    </div>
</div>

app/views/entries/show.html.erb
<% content_for :title do %>
  <%= @entry.meal_type %> &ndash; <%= DateTime.now.to_s(:nice_date) %>
<% end %>

<div class="columns mt-6 is-centered">
  <div class="column is-one-third">
    <nav class="panel is-link">
      <p class="panel-heading">
        <%= @entry.meal_type %>
      </p>

      <div class="panel-block">
        Calories:
        <%= @entry.calories %>
      </div>

      <div class="panel-block">
        Proteins:
        <%= @entry.proteins %>
      </div>


      <div class="panel-block">
        Carbohydrates:
        <%= @entry.carbohydrates %>
      </div>


      <div class="panel-block">
        Fats:
        <%= @entry.fats %>
      </div>
    </nav>
    <div class="columns is-mobile">
      <div class="column">
        <%= link_to 'Edit', edit_entry_path(@entry), class: "button is-gray" %> |
        <%= link_to 'Delete', entry_path(@entry), method: :delete, data: {confirm: "Are you sure?"}, class:"buttono is-gray" %>
      </div>
      <div class="column"></div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <% if notice.present? %>
    <div class="notification is-link is-light"><%= notice %></div>
    <% end %>

    <% if alert.present? %>
    <div class="notification is-danger is-light"><%= alert %></div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar is-link">
  <div class="container">
    <div id="navMenu" class="navbar-menu">
      <div class="navbar-start">
        <%= link_to root_path, class:"navbar-item" do%>
          <span class="has-text-weight-bold is-size-4 ml -4"></span>
        <% end %>
        <a class="navbar-item">
          Documentation
        </a>
      </div>

      <div class="navbar-end">
        <%= link_to "Create new entry", new_entry_path, class:"button is-success" %>
        <%# <span class="navbar-item">
            <%= link_to new_entry_path, class:"button is-success" do %>
           <%# <span>Create new entry</span>
            <% end %>
        <%#</span> %>
      </div>
    </div>
  </div>
</nav>
<div>
    <h1 class="title">
        <% if content_for(:title) %>
            <%= yield :title %> 
        <% else %>
            Foodlog
        <% end %>
    </h1>
</div>